birdName: "Lav69"
workingDir: "/mnt/work0/kbsuresh"
rigDir: "ksrig:ks_rig"


catGTparams:
  CATGTPATH: "/home/kbsuresh/snakeSort/CatGT-linux/runit.sh" # abs path
  filtmode: "gblcar"
  apfilter: "butter,12,300,9000"
  zerofillmax: "5"
  sepShanks: False



